"""Deterministic aggregate dispatcher code generation."""
from __future__ import annotations

from .constants import DISPATCH_RUNTIME_TEMPLATE
from .aggregate_dispatch import embed_bucket_sources
from .dispatch_signatures import build_generalized_dispatch_plan


def _generated_dispatch_runtime() -> str:
    """Runtime signature code shared semantically with collect_dispatch_signatures.py."""
    return DISPATCH_RUNTIME_TEMPLATE.read_text(encoding="utf-8").strip()


def build_deterministic_dispatcher(
    *,
    kind: str,
    signature_records: list[dict],
    bucket_by_index: dict[int, str],
    module_records: dict[str, dict],
    module_sources: dict[str, str],
) -> str:
    """Generate one self-contained kernel.py with statically embedded buckets."""
    bucket_names = sorted(module_records)
    if set(module_sources) != set(bucket_names):
        raise ValueError("embedded aggregate source set does not match module records")
    bucket_indices = {name: index for index, name in enumerate(bucket_names)}
    generalized_plan, _evidence = build_generalized_dispatch_plan(
        signature_records,
        {
            index: bucket_indices[name]
            for index, name in bucket_by_index.items()
        },
    )

    entry_name = "Model" if kind == "shapes" else "run" if kind == "sol" else ""
    if not entry_name:
        raise ValueError(f"unsupported deterministic dispatch kind: {kind}")
    embedded = embed_bucket_sources(module_sources, entry_name=entry_name)
    blob_map = {
        name: str(module_records[name].get("kernel_blob") or "")
        for name in bucket_names
    }
    header = (
        "# Generated by orchestrator/optimize.py. Do not edit.\n"
        "# Self-contained range dispatcher over independently validated bucket kernels.\n"
        f"from __future__ import {', '.join(embedded.future_features)}\n\n"
        "import math\n"
        "import torch\n\n"
        + "\n\n".join(embedded.blocks)
        + "\n\n"
        + _generated_dispatch_runtime()
        + "\n\n"
        + f"_BUCKET_KERNEL_BLOBS = {blob_map!r}\n"
        + f"_SCHEMA_TO_DISPATCH_TREE = {generalized_plan!r}\n"
        + "def _select_bucket(init_signature, args, kwargs):\n"
        + "    signature = (init_signature, _invocation_signature(args, kwargs))\n"
        + "    schema, features = _dispatch_schema_features(*signature)\n"
        + "    tree = _SCHEMA_TO_DISPATCH_TREE.get(schema)\n"
        + "    if tree is None:\n"
        + "        raise RuntimeError(f'no compatible workload bucket schema for signature: {signature!r}')\n"
        + "    return _dispatch_tree_bucket(tree, features)\n\n"
    )
    if kind == "shapes":
        models = ", ".join(embedded.entry_symbols)
        return header + f"_BUCKET_MODELS = ({models},)\n\n" + '''
class Model(torch.nn.Module):
    def __init__(self, *args, **kwargs):
        super().__init__()
        self._dispatch_init_args = args
        self._dispatch_init_kwargs = kwargs
        self._dispatch_init_signature = _invocation_signature(args, kwargs)
        self._dispatch_models = torch.nn.ModuleDict()

    def forward(self, *args, **kwargs):
        index = _select_bucket(self._dispatch_init_signature, args, kwargs)
        key = str(index)
        if key not in self._dispatch_models:
            candidate = _BUCKET_MODELS[index](
                *self._dispatch_init_args, **self._dispatch_init_kwargs
            )
            if not isinstance(candidate, torch.nn.Module):
                raise TypeError("bucket Model must inherit torch.nn.Module")
            anchor = _first_tensor((args, kwargs))
            if anchor is not None:
                candidate = candidate.to(anchor.device)
            candidate.train(self.training)
            self._dispatch_models[key] = candidate
        return self._dispatch_models[key](*args, **kwargs)
'''.lstrip()
    if kind == "sol":
        empty_init = (
            "invocation",
            (),
            (),
        )
        runners = ", ".join(embedded.entry_symbols)
        return header + f"_BUCKET_RUNNERS = ({runners},)\n\n" + f'''
def run(*args, **kwargs):
    index = _select_bucket({empty_init!r}, args, kwargs)
    return _BUCKET_RUNNERS[index](*args, **kwargs)
'''.lstrip()
    raise AssertionError("unreachable")
