#!/usr/bin/env python3

"""Generate (or verify) the flat content catalog ``docs/index.md``.

The index is a single page listing every content document under ``docs/`` with a
one-line summary, grouped by top-level domain. It is generated, never
hand-edited. Run with ``--check`` in CI to fail when the committed index drifts
from the tree.
"""

import argparse
import re
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Optional


GENERATED_BANNER = "<!-- generated by scripts/build_index.py; do not edit by hand -->"
INDEX_TITLE = "# GPU Wiki Index"
INDEX_SUMMARY = (
    "Flat catalog of every document under `docs/`, one line each, grouped by "
    "domain. Generated from the tree; do not edit by hand."
)

EXCLUDED_NAMES = {"README.md", "index.md"}
OVERVIEW_GROUP = "overview"
# Groups are the first two path components (e.g. "nvidia/blackwell", "amd/common");
# root-level pages (RELATIONS.md) go under OVERVIEW_GROUP. Order is OVERVIEW first,
# then the rest alphabetically — see ordered_groups().
GROUP_ORDER = (OVERVIEW_GROUP,)

H1_RE = re.compile(r"^#\s+(.+?)\s*$")
H2_RE = re.compile(r"^##\s+(.+?)\s*$")
HEADING_RE = re.compile(r"^#{1,6}\s")
METADATA_RE = re.compile(r"^\*\*[^*]+\*\*:")
FENCE_RE = re.compile(r"^\s{0,3}(`{3,}|~{3,})")
INLINE_LINK_RE = re.compile(r"\[([^\]\n]+)\]\([^)\n]+\)")
WHITESPACE_RE = re.compile(r"\s+")
SUMMARY_MAX = 140

# Lines containing one of these markers are skipped as summary candidates so the
# generated index never copies an environment-specific path out of its
# provenance context (which would turn a non-blocking note into a blocking one).
RISKY_PATH_MARKERS = (
    "/Users/",
    "/home/",
    "/root/",
    "/workspace/",
    "/private/",
    "/gpu-wiki/",
)


@dataclass(frozen=True)
class Entry:
    group: str
    rel_path: str  # path relative to docs/
    title: str
    summary: str


def mask_fences(lines: list[str]) -> list[str]:
    """Blank out fenced code blocks so '# ...' comments inside code are not
    mistaken for headings. Line count is preserved so indices stay valid."""
    masked: list[str] = []
    in_fence = False
    for line in lines:
        if FENCE_RE.match(line):
            in_fence = not in_fence
            masked.append("")
            continue
        masked.append("" if in_fence else line)
    return masked


def extract_title(lines: list[str], stem: str) -> tuple[str, int]:
    """Return (title, index of the title line or -1)."""
    for idx, line in enumerate(lines):
        match = H1_RE.match(line)
        if match:
            return match.group(1).strip(), idx
    for idx, line in enumerate(lines):
        match = H2_RE.match(line)
        if match:
            return match.group(1).strip(), idx
    return stem, -1


def is_summary_candidate(line: str) -> bool:
    stripped = line.strip()
    if not stripped:
        return False
    if HEADING_RE.match(stripped):
        return False
    if METADATA_RE.match(stripped):
        return False
    if FENCE_RE.match(line):
        return False
    if stripped.startswith("|"):
        return False
    if stripped.startswith(">"):
        return False
    if stripped.startswith("<!--"):
        return False
    if stripped == "---":
        return False
    if any(marker in stripped for marker in RISKY_PATH_MARKERS):
        return False
    return True


def sanitize_summary(text: str) -> str:
    text = INLINE_LINK_RE.sub(r"\1", text)
    text = text.replace("[", "").replace("]", "")
    text = WHITESPACE_RE.sub(" ", text).strip()
    if len(text) > SUMMARY_MAX:
        text = text[: SUMMARY_MAX - 1].rstrip() + "…"
    return text


def extract_summary(lines: list[str], title_index: int) -> str:
    in_fence = False
    for line in lines[title_index + 1 :]:
        if FENCE_RE.match(line):
            in_fence = not in_fence
            continue
        if in_fence:
            continue
        if is_summary_candidate(line):
            summary = sanitize_summary(line)
            if summary:
                return summary
    return "(no summary)"


def group_for(rel_path: Path) -> str:
    parts = rel_path.parts
    if len(parts) == 1:
        return OVERVIEW_GROUP
    if len(parts) == 2:
        return parts[0]  # file directly under a vendor dir, e.g. generic/foo.md
    return "/".join(parts[:2])


def collect_entries(docs_dir: Path) -> list[Entry]:
    entries: list[Entry] = []
    for path in sorted(docs_dir.rglob("*.md")):
        if path.name in EXCLUDED_NAMES:
            continue
        rel_path = path.relative_to(docs_dir)
        text = path.read_text(encoding="utf-8", errors="ignore")
        lines = mask_fences(text.splitlines())
        title, title_index = extract_title(lines, rel_path.stem)
        summary = extract_summary(lines, title_index)
        entries.append(
            Entry(
                group=group_for(rel_path),
                rel_path=rel_path.as_posix(),
                title=title,
                summary=summary,
            )
        )
    return entries


def ordered_groups(entries: list[Entry]) -> list[str]:
    present = {entry.group for entry in entries}
    ordered = [group for group in GROUP_ORDER if group in present]
    extra = sorted(group for group in present if group not in GROUP_ORDER)
    return ordered + extra


def render_index(entries: list[Entry]) -> str:
    lines = [INDEX_TITLE, "", INDEX_SUMMARY, "", GENERATED_BANNER, ""]
    for group in ordered_groups(entries):
        group_entries = sorted(
            (entry for entry in entries if entry.group == group),
            key=lambda entry: entry.rel_path,
        )
        lines.append(f"## {group}")
        lines.append("")
        for entry in group_entries:
            lines.append(f"- [{entry.rel_path}]({entry.rel_path}) — {entry.summary}")
        lines.append("")
    return "\n".join(lines).rstrip("\n") + "\n"


def main(argv: Optional[list[str]] = None) -> int:
    parser = argparse.ArgumentParser(description="Build or verify gpu-wiki/docs/index.md.")
    parser.add_argument("--root", default="gpu-wiki", help="Path to the gpu-wiki root.")
    parser.add_argument(
        "--check",
        action="store_true",
        help="Verify the committed index matches the tree; do not write.",
    )
    args = parser.parse_args(argv)

    root = Path(args.root)
    docs_dir = root / "docs"
    if not docs_dir.is_dir():
        print(f"ERROR docs-not-found {docs_dir}:1 path does not exist", file=sys.stderr)
        return 1

    index_path = docs_dir / "index.md"
    content = render_index(collect_entries(docs_dir))

    if args.check:
        current = index_path.read_text(encoding="utf-8") if index_path.is_file() else None
        if current == content:
            print("gpu-wiki index is up to date.")
            return 0
        reason = "missing" if current is None else "out of date"
        print(
            f"ERROR index-drift {index_path}:1 docs/index.md is {reason}; "
            f"run: python3 gpu-wiki/scripts/build_index.py --root {args.root}",
            file=sys.stderr,
        )
        return 1

    index_path.write_text(content, encoding="utf-8")
    print(f"Wrote {index_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
