"""Private plugin subprocess. The HTTP handler owns authorization and deadlines."""
from __future__ import annotations

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from orchestrator.plugins import PluginRegistry  # noqa: E402
from plugin_runtime.schema import decode_json  # noqa: E402


def load_pinned_registry(request: dict) -> PluginRegistry:
    """Revalidate only the selected plugin against the private Supervisor snapshot."""
    snapshot = request["snapshot"]
    plugin_id, separator, tool_name = request["tool"].partition(".")
    selected = [item for item in snapshot["plugins"] if item["id"] == plugin_id]
    if not separator or not tool_name or len(selected) != 1:
        raise RuntimeError("Tool is not uniquely bound to the Supervisor plugin snapshot")
    registry = PluginRegistry(plugin_root=Path(selected[0]["root"]))
    if registry.snapshot() != dict(snapshot, plugins=selected):
        raise RuntimeError("Plugin inputs changed; restart the Supervisor with the new catalog")
    return registry


def main() -> int:
    # Both paths are generated by the Supervisor, never accepted from Agent argv.
    request = decode_json(Path(sys.argv[1]).read_text())
    registry = load_pinned_registry(request)
    workspace = Path.cwd()
    # The Supervisor already applied its cached manifest environment and scoped
    # Campaign identity. Do not rebuild the unrelated catalogs to reconstruct it.
    result = registry.call(request["tool"], request["input"], workspace, supervised=True)
    print(json.dumps(result, ensure_ascii=False, allow_nan=False))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
