"""Private plugin subprocess. The HTTP handler owns authorization and deadlines."""
from __future__ import annotations

import json
import os
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from orchestrator.plugins import PluginRegistry
from plugin_runtime.schema import decode_json


def main() -> int:
    # Both paths are generated by the Supervisor, never accepted from Agent argv.
    request = decode_json(Path(sys.argv[1]).read_text())
    registry = PluginRegistry()
    if registry.snapshot() != request["snapshot"]:
        raise RuntimeError("Plugin inputs changed; restart the Supervisor with the new catalog")
    workspace = Path.cwd()
    environment = registry.environment(workspace)
    environment.update({key: os.environ[key] for key in
                        ("ATREX_WIKI_PROFILE_ROOT", "ATREX_WIKI_TASK_ID") if key in os.environ})
    os.environ.update(environment)
    result = registry.call(request["tool"], request["input"], workspace, supervised=True)
    print(json.dumps(result, ensure_ascii=False, allow_nan=False))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
