"""Private plugin subprocess. The HTTP handler owns authorization and deadlines."""
from __future__ import annotations

import json
import sys
import traceback
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from orchestrator.plugins import PluginRegistry
from plugin_runtime.schema import PluginError, decode_json

from supervisor.plugin_output import (
    MAX_OUTPUT_BYTES,
    OUTPUT_ERROR_EXIT_CODE,
    OUTPUT_ERROR_FIELD,
)


def load_pinned_registry(request: dict) -> PluginRegistry:
    """Revalidate only the selected plugin against the private Supervisor snapshot."""
    snapshot = request["snapshot"]
    plugin_id, separator, tool_name = request["tool"].partition(".")
    selected = [item for item in snapshot["plugins"] if item["id"] == plugin_id]
    if not separator or not tool_name or len(selected) != 1:
        raise RuntimeError("Tool is not uniquely bound to the Supervisor plugin snapshot")
    registry = PluginRegistry(plugin_root=Path(selected[0]["root"]))
    if registry.snapshot() != dict(snapshot, plugins=selected):
        raise RuntimeError("Plugin inputs changed; restart the Supervisor with the new catalog")
    return registry


def main() -> int:
    # Both paths are generated by the Supervisor, never accepted from Agent argv.
    request = decode_json(Path(sys.argv[1]).read_text())
    registry = load_pinned_registry(request)
    workspace = Path.cwd()
    # The Supervisor already applied its cached manifest environment and scoped
    # Campaign identity. Do not rebuild the unrelated catalogs to reconstruct it.
    try:
        result = registry.call(request["tool"], request["input"], workspace, supervised=True)
    except PluginError as error:
        if error.code != "invalid_output":
            raise
        # Keep the diagnostic private; do not turn all nonzero process exits
        # into this known-output classification.
        traceback.print_exc(file=sys.stderr)
        print(json.dumps({OUTPUT_ERROR_FIELD: "invalid_output"}))
        return OUTPUT_ERROR_EXIT_CODE
    rendered = json.dumps(result, ensure_ascii=False, allow_nan=False) + "\n"
    if len(rendered.encode()) > MAX_OUTPUT_BYTES:
        # Emit a small status instead of hitting the parent executor's larger
        # transport cap, which would otherwise erase this known outcome.
        print(json.dumps({OUTPUT_ERROR_FIELD: "result_too_large"}))
        return OUTPUT_ERROR_EXIT_CODE
    sys.stdout.write(rendered)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
