#!/usr/bin/env bash
set -euo pipefail

# gpu-wiki archive note:
# Build helper for the experimental task39 prefill_mma_padded SM120 source.
# This is retained for reproducibility of the archived candidate, not as a
# generic build recipe.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SRC="${SCRIPT_DIR}/prefill_mma_padded_sm120_experimental.cu"
OUT="${SCRIPT_DIR}/prefill_mma_padded_sm120_experimental.so"
NVCC_BIN="${NVCC:-/usr/local/cuda/bin/nvcc}"
if [ -z "${CUTLASS_DIR:-}" ]; then
  echo "CUTLASS_DIR must point to a CUTLASS checkout." >&2
  echo "Example: export CUTLASS_DIR=/path/to/cutlass" >&2
  exit 2
fi

CUTLASS_OVERRIDE_DIR="${CUTLASS_OVERRIDE_DIR:-${SCRIPT_DIR}/cutlass_override}"
USE_PREFILL_TMA_B="${USE_PREFILL_TMA_B:-1}"
USE_PREFILL_TMA_BREP="${USE_PREFILL_TMA_BREP:-0}"
USE_PREFILL_TMA_PAIR_M="${USE_PREFILL_TMA_PAIR_M:-0}"
USE_PREFILL_WS_TMA_BREP="${USE_PREFILL_WS_TMA_BREP:-0}"
PREFILL_ENABLE_M64X2_WIDE_N_ROUTE="${PREFILL_ENABLE_M64X2_WIDE_N_ROUTE:-0}"
PREFILL_ENABLE_M64X2_MIXED3_ROUTE="${PREFILL_ENABLE_M64X2_MIXED3_ROUTE:-0}"
PREFILL_ENABLE_M64_N2_AREUSE_ROUTE="${PREFILL_ENABLE_M64_N2_AREUSE_ROUTE:-0}"
PREFILL_ENABLE_WS_TMA_BREP_ROUTE="${PREFILL_ENABLE_WS_TMA_BREP_ROUTE:-0}"
PREFILL_ENABLE_SCALE_BCAST="${PREFILL_ENABLE_SCALE_BCAST:-0}"
PREFILL_ENABLE_CLUSTER_ROUTE="${PREFILL_ENABLE_CLUSTER_ROUTE:-0}"
PREFILL_CLUSTER_X="${PREFILL_CLUSTER_X:-2}"
PREFILL_CLUSTER_SCHED_POLICY="${PREFILL_CLUSTER_SCHED_POLICY:-2}"
PREFILL_ENABLE_PERSIST_L2="${PREFILL_ENABLE_PERSIST_L2:-0}"
PREFILL_ENABLE_PERSISTENT_CTA_ROUTE="${PREFILL_ENABLE_PERSISTENT_CTA_ROUTE:-0}"
PREFILL_PERSISTENT_CTAS_PER_SM="${PREFILL_PERSISTENT_CTAS_PER_SM:-2}"
PREFILL_PERSISTENT_CTA_COUNT="${PREFILL_PERSISTENT_CTA_COUNT:-0}"
PREFILL_PERSIST_HIT_RATIO_X100="${PREFILL_PERSIST_HIT_RATIO_X100:-60}"
PREFILL_PERSIST_MAX_BYTES="${PREFILL_PERSIST_MAX_BYTES:-0}"
PREFILL_REPACK_THREADS="${PREFILL_REPACK_THREADS:-256}"
PREFILL_WS_PRODUCER_REGS="${PREFILL_WS_PRODUCER_REGS:-40}"
PREFILL_WS_CONSUMER_REGS="${PREFILL_WS_CONSUMER_REGS:-112}"
PREFILL_ENABLE_CUTLASS_WS_ROUTE="${PREFILL_ENABLE_CUTLASS_WS_ROUTE:-0}"
PREFILL_CUTLASS_INLINE_ALPHA_ONE="${PREFILL_CUTLASS_INLINE_ALPHA_ONE:-0}"
PREFILL_CUTLASS_DIRECT_RUN="${PREFILL_CUTLASS_DIRECT_RUN:-1}"
PREFILL_CUTLASS_DOWN1024_MODE="${PREFILL_CUTLASS_DOWN1024_MODE:-2}"
PREFILL_CUTLASS_SCHEDULER_KIND="${PREFILL_CUTLASS_SCHEDULER_KIND:-0}"
PREFILL_CUTLASS_NO_SOURCE_C="${PREFILL_CUTLASS_NO_SOURCE_C:-1}"
PREFILL_CUTLASS_GATEUP_MODE="${PREFILL_CUTLASS_GATEUP_MODE:-0}"
PREFILL_CUTLASS_M256_STAGE_COUNT="${PREFILL_CUTLASS_M256_STAGE_COUNT:-0}"
PREFILL_CUTLASS_M256_SCHEDULE_KIND="${PREFILL_CUTLASS_M256_SCHEDULE_KIND:-0}"
PREFILL_CUTLASS_EPILOGUE_TILE="${PREFILL_CUTLASS_EPILOGUE_TILE:-2}"
PREFILL_CUTLASS_M256_EPILOGUE_TILE="${PREFILL_CUTLASS_M256_EPILOGUE_TILE:-${PREFILL_CUTLASS_EPILOGUE_TILE}}"
PREFILL_CUTLASS_SF_COPY_ATOM="${PREFILL_CUTLASS_SF_COPY_ATOM:-0}"
PREFILL_CUTLASS_SF_COPY_ORDER="${PREFILL_CUTLASS_SF_COPY_ORDER:-0}"
PREFILL_CUTLASS_SF_SMEM_ALIGN="${PREFILL_CUTLASS_SF_SMEM_ALIGN:-16}"
PREFILL_CUTLASS_SF_SMEM_LAYOUT_MODE="${PREFILL_CUTLASS_SF_SMEM_LAYOUT_MODE:-0}"
PREFILL_CUTLASS_WAIT_MODE="${PREFILL_CUTLASS_WAIT_MODE:-0}"
PREFILL_CUTLASS_ATOM_LAYOUT_MODE="${PREFILL_CUTLASS_ATOM_LAYOUT_MODE:-0}"
PREFILL_EXTRA_NVCC_FLAGS="${PREFILL_EXTRA_NVCC_FLAGS:-}"

if [[ ! -x "${NVCC_BIN}" ]]; then
  echo "nvcc not found or not executable: ${NVCC_BIN}" >&2
  exit 1
fi

"${NVCC_BIN}" \
  -O3 \
  --use_fast_math \
  -std=c++17 \
  -gencode=arch=compute_120a,code=sm_120a \
  --expt-relaxed-constexpr \
	  -diag-suppress=20013,20015 \
	  ${PREFILL_EXTRA_NVCC_FLAGS} \
	  -Xcompiler=-fPIC \
	  -Xptxas=-v \
	  -I"${CUTLASS_OVERRIDE_DIR}/include" \
	  -I"${CUTLASS_DIR}/include" \
	  -I"${CUTLASS_DIR}/tools/util/include" \
  -DUSE_PREFILL_TMA_B="${USE_PREFILL_TMA_B}" \
  -DUSE_PREFILL_TMA_BREP="${USE_PREFILL_TMA_BREP}" \
  -DUSE_PREFILL_TMA_PAIR_M="${USE_PREFILL_TMA_PAIR_M}" \
  -DUSE_PREFILL_WS_TMA_BREP="${USE_PREFILL_WS_TMA_BREP}" \
  -DPREFILL_ENABLE_M64X2_WIDE_N_ROUTE="${PREFILL_ENABLE_M64X2_WIDE_N_ROUTE}" \
  -DPREFILL_ENABLE_M64X2_MIXED3_ROUTE="${PREFILL_ENABLE_M64X2_MIXED3_ROUTE}" \
  -DPREFILL_ENABLE_M64_N2_AREUSE_ROUTE="${PREFILL_ENABLE_M64_N2_AREUSE_ROUTE}" \
  -DPREFILL_ENABLE_WS_TMA_BREP_ROUTE="${PREFILL_ENABLE_WS_TMA_BREP_ROUTE}" \
  -DPREFILL_ENABLE_SCALE_BCAST="${PREFILL_ENABLE_SCALE_BCAST}" \
  -DPREFILL_ENABLE_CLUSTER_ROUTE="${PREFILL_ENABLE_CLUSTER_ROUTE}" \
  -DPREFILL_CLUSTER_X="${PREFILL_CLUSTER_X}" \
  -DPREFILL_CLUSTER_SCHED_POLICY="${PREFILL_CLUSTER_SCHED_POLICY}" \
  -DPREFILL_ENABLE_PERSIST_L2="${PREFILL_ENABLE_PERSIST_L2}" \
  -DPREFILL_ENABLE_PERSISTENT_CTA_ROUTE="${PREFILL_ENABLE_PERSISTENT_CTA_ROUTE}" \
  -DPREFILL_PERSISTENT_CTAS_PER_SM="${PREFILL_PERSISTENT_CTAS_PER_SM}" \
  -DPREFILL_PERSISTENT_CTA_COUNT="${PREFILL_PERSISTENT_CTA_COUNT}" \
  -DPREFILL_PERSIST_HIT_RATIO_X100="${PREFILL_PERSIST_HIT_RATIO_X100}" \
  -DPREFILL_PERSIST_MAX_BYTES="${PREFILL_PERSIST_MAX_BYTES}" \
  -DPREFILL_REPACK_THREADS="${PREFILL_REPACK_THREADS}" \
  -DPREFILL_WS_PRODUCER_REGS="${PREFILL_WS_PRODUCER_REGS}" \
  -DPREFILL_WS_CONSUMER_REGS="${PREFILL_WS_CONSUMER_REGS}" \
  -DPREFILL_ENABLE_CUTLASS_WS_ROUTE="${PREFILL_ENABLE_CUTLASS_WS_ROUTE}" \
  -DPREFILL_CUTLASS_INLINE_ALPHA_ONE="${PREFILL_CUTLASS_INLINE_ALPHA_ONE}" \
  -DPREFILL_CUTLASS_DIRECT_RUN="${PREFILL_CUTLASS_DIRECT_RUN}" \
  -DPREFILL_CUTLASS_DOWN1024_MODE="${PREFILL_CUTLASS_DOWN1024_MODE}" \
  -DPREFILL_CUTLASS_SCHEDULER_KIND="${PREFILL_CUTLASS_SCHEDULER_KIND}" \
  -DPREFILL_CUTLASS_NO_SOURCE_C="${PREFILL_CUTLASS_NO_SOURCE_C}" \
  -DPREFILL_CUTLASS_GATEUP_MODE="${PREFILL_CUTLASS_GATEUP_MODE}" \
  -DPREFILL_CUTLASS_M256_STAGE_COUNT="${PREFILL_CUTLASS_M256_STAGE_COUNT}" \
	  -DPREFILL_CUTLASS_M256_SCHEDULE_KIND="${PREFILL_CUTLASS_M256_SCHEDULE_KIND}" \
	  -DPREFILL_CUTLASS_EPILOGUE_TILE="${PREFILL_CUTLASS_EPILOGUE_TILE}" \
	  -DPREFILL_CUTLASS_M256_EPILOGUE_TILE="${PREFILL_CUTLASS_M256_EPILOGUE_TILE}" \
	  -DCUTLASS_SM120_BLOCKSCALED_USE_SF_COPY_ATOM="${PREFILL_CUTLASS_SF_COPY_ATOM}" \
	  -DCUTLASS_SM120_BLOCKSCALED_SF_COPY_ORDER="${PREFILL_CUTLASS_SF_COPY_ORDER}" \
	  -DCUTLASS_SM120_BLOCKSCALED_SF_SMEM_ALIGN="${PREFILL_CUTLASS_SF_SMEM_ALIGN}" \
	  -DCUTLASS_SM120_BLOCKSCALED_SF_SMEM_LAYOUT_MODE="${PREFILL_CUTLASS_SF_SMEM_LAYOUT_MODE}" \
	  -DCUTLASS_SM120_BLOCKSCALED_WAIT_MODE="${PREFILL_CUTLASS_WAIT_MODE}" \
	  -DCUTLASS_SM120_BLOCKSCALED_ATOM_LAYOUT_MODE="${PREFILL_CUTLASS_ATOM_LAYOUT_MODE}" \
	  --shared \
  "${SRC}" \
  -cudart shared \
  -lcuda \
  -o "${OUT}"

echo "${OUT}"
